### ISSUE TITLE
Spawning without weapons

### ISSUE THREAD

**Issue by Rafael-Leal-Prada-dos-Santos** [boomix/csgo-duels#16]
I'm respawning without weapons after last update :/ this plugin is not being updated anymore?

**Comment by boomix** [comment]
Just checked with the latest version, did not have any problems. 
Make sure you have added all translation files and check if you have any error logs.

**Comment by Rafael-Leal-Prada-dos-Santos** [comment]
I fixed. It was the version of sourmod and metamod source, I updated both to the actual dev versions and it's working again
