### ISSUE TITLE
MEMORY LEAK DETECTED IN PLUGIN

### ISSUE THREAD

**Issue by SeatloN** [boomix/csgo-duels#2]
L 05/15/2017 - 17:54:20: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "1v1DM.smx")
L 05/15/2017 - 17:54:20: [SM] Unloading plugin to free 32326 handles.
L 05/15/2017 - 17:54:20: [SM] Contact the author(s) of this plugin to correct this error.
L 05/15/2017 - 17:54:20: --------------------------------------------------------------------------
L 05/15/2017 - 17:54:20: Type	GameEvent           |	Count	9267
L 05/15/2017 - 17:54:20: Type	IBaseMenu           |	Count	1232
L 05/15/2017 - 17:54:20: Type	DataPack            |	Count	3
L 05/15/2017 - 17:54:20: Type	Timer               |	Count	8
L 05/15/2017 - 17:54:20: Type	CellArray           |	Count	21811
L 05/15/2017 - 17:54:20: Type	Cookie              |	Count	5
L 05/15/2017 - 17:54:20: -- Approximately 5945420 bytes of memory are in use by (32326) Handles.

L 05/15/2017 - 21:20:32: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "1v1DM.smx")
L 05/15/2017 - 21:20:32: [SM] Unloading plugin to free 32313 handles.
L 05/15/2017 - 21:20:32: [SM] Contact the author(s) of this plugin to correct this error.
L 05/15/2017 - 21:20:32: --------------------------------------------------------------------------
L 05/15/2017 - 21:20:32: Type	GameEvent           |	Count	9125
L 05/15/2017 - 21:20:32: Type	IBaseMenu           |	Count	1234
L 05/15/2017 - 21:20:32: Type	Timer               |	Count	5
L 05/15/2017 - 21:20:32: Type	CellArray           |	Count	21944
L 05/15/2017 - 21:20:32: Type	Cookie              |	Count	5
L 05/15/2017 - 21:20:32: -- Approximately 5622392 bytes of memory are in use by (32313) Handles.

L 05/16/2017 - 18:57:09: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "1v1DM.smx")
L 05/16/2017 - 18:57:09: [SM] Unloading plugin to free 32322 handles.
L 05/16/2017 - 18:57:09: [SM] Contact the author(s) of this plugin to correct this error.
L 05/16/2017 - 18:57:09: --------------------------------------------------------------------------
L 05/16/2017 - 18:57:09: Type	GameEvent           |	Count	10009
L 05/16/2017 - 18:57:09: Type	IBaseMenu           |	Count	1185
L 05/16/2017 - 18:57:09: Type	Timer               |	Count	7
L 05/16/2017 - 18:57:09: Type	CellArray           |	Count	21116
L 05/16/2017 - 18:57:09: Type	Cookie              |	Count	5
L 05/16/2017 - 18:57:09: -- Approximately 6467592 bytes of memory are in use by (32322) Handles.

L 05/17/2017 - 15:49:49: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "1v1DM.smx")
L 05/17/2017 - 15:49:49: [SM] Unloading plugin to free 32325 handles.
L 05/17/2017 - 15:49:49: [SM] Contact the author(s) of this plugin to correct this error.
L 05/17/2017 - 15:49:49: --------------------------------------------------------------------------
L 05/17/2017 - 15:49:49: Type	GameEvent           |	Count	8957
L 05/17/2017 - 15:49:49: Type	IBaseMenu           |	Count	1135
L 05/17/2017 - 15:49:49: Type	Timer               |	Count	5
L 05/17/2017 - 15:49:49: Type	CellArray           |	Count	22223
L 05/17/2017 - 15:49:49: Type	Cookie              |	Count	5
L 05/17/2017 - 15:49:49: -- Approximately 6107740 bytes of memory are in use by (32325) Handles.

**Comment by boomix** [comment]
Try out the latest version, should be fixed!

Thanks zipcore for helping out.
